### ISSUE TITLE
admin 登录没权限啊

### ISSUE THREAD

**Issue by xiejunping** [dnyz520/careyshop-admin#1]
按照提示跟本进不去呢？
希望发个账号看看demo  417663733@qq.com

**Comment by dnyz520** [comment]
> 按照提示跟本进不去呢？
> 希望发个账号看看demo [417663733@qq.com](mailto:417663733@qq.com)

为避免相同账号多人登录而被踢下线，可使用账号"admin1~admin45"进行登录，密码全部为"admin888"。
